### PR TITLE
649 show freezed helpers

### PR DESCRIPTION
**Pull request by lionsh29**
now you can use the checkbox to indicate if you want to search for all helpers.
I didn't want to add additional lang string, so used showAll

### CODE REVIEW

**Review by morfi11 — CHANGES_REQUESTED** [review]
need to change the text to "show frozen". Show all will certainly confuse the dist-admins and they might assign to frozen helpers this way :(

**Review by morfi11 — CHANGES_REQUESTED** [review]
@noam-honig - are you able to automatically fix the language back to what we have in master?

**Comment by noam-honig** [comment]
Not sure that I understand what you mean.
Please clarify and also include a specific term that you’re referring to

**Comment by lionsh29** [comment]
I've added a string to translations (showFreezed) and ran build-languages. it made some changes on the lang files, including strings I've not created

**Comment by noam-honig** [comment]
I see. It’ll be ok when I merge it

**Review by morfi11 — APPROVED** [review]
approve with assumption that @noam-honig  will fix the bad strings :)

**Pull request merged**
